.
htmlacademy-htmlcss/1844021-sedona-34 pull request #4
Opened 2022-06-05 00:36 UTC by KudrenkoArtem

2022-06-06 06:51 UTC, baronin requested changes
Привет
1) Почему не форматируешь документ ?:) 
2) Не прошла проверка в валидаторе
![image](https://user-images.githubusercontent.com/20131942/172110096-0c6ce208-0805-459c-9b62-e154d31d5a24.png)
Это каталог
![image](https://user-images.githubusercontent.com/20131942/172110163-436795ad-6ac8-4a68-b367-2e980f903904.png)

Вот css
![image](https://user-images.githubusercontent.com/20131942/172110510-e8b90e9e-b492-45a1-8848-8359ceef65be.png)

2022-06-06 06:51 UTC, baronin commented on catalog.html
> +          <a class="pagination-link-one" href="">1</a>
почему тут переделано ?

2022-06-06 06:51 UTC, baronin commented on catalog.html
> +    <section class="newsletter-catalog">
почему к newsletter решил добавить тут каталог ?

2022-06-06 06:51 UTC, baronin commented on catalog.html
> +      <b class="newsletter-subscribe-catalog">Подпишитесь на рассылку</b>
Если ты к родителю добавил newsletter-**catalog** - то нужно это сделать и по всей секции 
newsletter-catalog-subscribe

2022-06-06 06:51 UTC, baronin commented on catalog.html
> +        <button class="button-newsletter-button" type="submit">
мне кажется что button -  это должен быть отдельный класс для всех кнопок, где будут базовые стили(то есть это было правильно)

Сейчас ты к button добавил **-newsletter-button**, но у нас секция называется newsletter-catalog
Тогда правильно будет newsletter-catalog-button

2022-06-06 06:51 UTC, baronin commented on catalog.html
>            <span class="visually-hidden">Подписаться</span>
Подписаться - ты скрываешь эту надпись, почему ? в макете она есть и ее видно

2022-06-06 06:51 UTC, baronin commented on index.html
> +        <li class="advices-item-souvenirs">
Почему ты переделал ? Было же все нормально

2022-06-06 06:51 UTC, baronin commented on styles/styles.css
> +.advices-item-tourist{
`.advices-item-souvenirs{
    color: #333333;
    background-color: rgba(131, 179, 211, 0.12);
    text-align: center;
}
.advices-item-square{
    columns: #333333;
    background-color: rgba(131, 179, 211, 0.12);
    text-align: center;
}
.advices-item-road{
    columns: #333333;
    background-color: rgba(131, 179, 211, 0.2);
    text-align: center;
}
.advices-item-tourist{
    color: #333333;
    background-color: rgba(131, 179, 211, 0.12);
    text-align: center;
}`

У всех этих классов, одинаковые свойства, может лучше сделать для этого один класс что бы не дублирвоть ?

2022-06-06 06:51 UTC, baronin commented on styles/styles.css
> +
Зачем тут отступы ?:)

2022-06-06 06:51 UTC, baronin commented on styles/styles.css
> +    color: white;
Во всем проекте ты указываешь цвет в хекс, а тут white, исправь пожалуйста на хекс, мы должни придерживатся единообразного написания кода

2022-06-09 06:20 UTC, baronin requested changes

2022-06-09 06:20 UTC, baronin commented on index.html
> +          <span class="subscribe">Отправить</span>
На макете "Подписаться" и нету стилей на эту форму

2022-06-09 09:28 UTC, KudrenkoArtem commented on catalog.html
>            <span class="visually-hidden">Подписаться</span>
Не подумал об этом, уже исправил)

2022-06-09 09:33 UTC, KudrenkoArtem commented on catalog.html
> +    <section class="newsletter-catalog">
там же нет фона на странице каталога, и цвет текста другой,или же можно было просто добавить через пробел второй класс?по типу class="newsletter newsletter-catalog"?

2022-06-10 08:43 UTC, merged