ДЗ НОМЕР 6
htmlacademy-htmlcss/1844021-sedona-34 pull request #6
Opened 2022-06-28 16:55 UTC by KudrenkoArtem

2022-06-29 05:21 UTC, baronin requested changes

2022-06-29 05:21 UTC, baronin commented on catalog.html
>              <ul class="footer-social-list">
Не проходим по пункту переполнение
![image](https://user-images.githubusercontent.com/20131942/176357371-cb537e29-a1a3-4dc2-8f70-946a6c085025.png)

2022-06-29 05:21 UTC, baronin commented on styles/styles.css
>  .search-hotel {
search-hotel - не понятно к чему относится, мне пришлось смотреть в инспекторе элементов, давай назовем явно btn-search-hotel

Зачем тут height?

2022-06-30 09:45 UTC, KudrenkoArtem commented on styles/styles.css
>  .search-hotel {
height дейстительно не за чем))

2022-06-30 10:10 UTC, merged